import type { Metadata } from 'next'
import { Quantico } from 'next/font/google'
import ThemeProvider from '@/components/global/layouts/providers/ThemeProvider'
import '@/assets/styles/globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const quantico = Quantico({
  variable: '--font-quantico',
  subsets: ['latin'],
  weight: ['400', '700'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${quantico.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          theme="light"
          forceTheme="light"
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
